import simpleFragmentShader from '../assets/simple_es3.frag';
import simpleVertexShader from '../assets/simple_es3.vert';
import textureFragmentES1Shader from '../assets/texture_es1.frag';
import textureFragmentES3Shader from '../assets/texture_es3.frag';
import textureFuncFragmentES3Shader from '../assets/texture_func_es3.frag';
import dynamicTemplateFragmentShader from '../assets/dynamic_template_es1.frag';
import insertDefinitionVertexShader from '../assets/insert_definition_es3.vert';
import reflectionVertexES1Shader from '../assets/reflection_es1.vert';
import reflectionVertexES3Shader from '../assets/reflection_es3.vert';
import layoutUniformFragmentES3Shader from '../assets/layout_uniform_es3.frag';
import precisionES3Shader from '../assets/precision_es3.vert';

exports.simpleFragment = simpleFragmentShader;
exports.simpleVertex = simpleVertexShader;
exports.textureFragmentES1 = textureFragmentES1Shader;
exports.textureFragmentES3 = textureFragmentES3Shader;
exports.textureFuncFragmentES3 = textureFuncFragmentES3Shader;
exports.dynamicTemplateFragment = dynamicTemplateFragmentShader;
exports.insertDefinitionVertex = insertDefinitionVertexShader;
exports.reflectionVertexES1 = reflectionVertexES1Shader;
exports.reflectionVertexES3 = reflectionVertexES3Shader;
exports.layoutUniformFragmentES3 = layoutUniformFragmentES3Shader;
exports.precisionES3 = precisionES3Shader;
