import simpleFragmentShader from '../assets/simple_es3.frag';
import simpleVertexShader from '../assets/simple_es3.vert';
import textureFragmentES1Shader from '../assets/texture_es1.frag';
import textureFragmentES3Shader from '../assets/texture_es3.frag';
import textureFuncFragmentES3Shader from '../assets/texture_func_es3.frag';
import textureFuncVertexES3Shader from '../assets/texture_func_es3.vert';
import textureFuncComplicatedES3Shader from '../assets/texture_func_complicated_es3.frag';
import dynamicTemplateFragmentShader from '../assets/dynamic_template_es1.frag';
import insertDefinitionVertexShader from '../assets/insert_definition_es3.vert';
import reflectionVertexES1Shader from '../assets/reflection_es1.vert';
import reflectionVertexES3Shader from '../assets/reflection_es3.vert';
import layoutUniformFragmentES3Shader from '../assets/layout_uniform_es3.frag';
import precisionES3Shader from '../assets/precision_es3.vert';
import attributeAndVaryingPrecisionES3Shader from '../assets/attribute_and_varying_precision_es3.vert';
import layoutAttributeES3Shader from '../assets/layout_attribute_es3.vert';
import outToGlFragColorES3Shader from '../assets/out_to_gl_frag_color.frag';
import smoothVaryingES3Shader from '../assets/smooth_varying_es3.vert';
import outQualifierFragmentES3Shader from '../assets/out_qualifier_fragment_es3.frag';
import ifdefFragmentShader from '../assets/ifdef.frag';
import ifdef2FragmentShader from '../assets/ifdef2.frag';

exports.simpleFragment = simpleFragmentShader;
exports.simpleVertex = simpleVertexShader;
exports.textureFragmentES1 = textureFragmentES1Shader;
exports.textureFragmentES3 = textureFragmentES3Shader;
exports.textureFuncFragmentES3 = textureFuncFragmentES3Shader;
exports.textureFuncVertexES3 = textureFuncVertexES3Shader;
exports.textureFuncComplicatedES3Shader = textureFuncComplicatedES3Shader;
exports.dynamicTemplateFragment = dynamicTemplateFragmentShader;
exports.insertDefinitionVertex = insertDefinitionVertexShader;
exports.reflectionVertexES1 = reflectionVertexES1Shader;
exports.reflectionVertexES3 = reflectionVertexES3Shader;
exports.layoutUniformFragmentES3 = layoutUniformFragmentES3Shader;
exports.precisionES3 = precisionES3Shader;
exports.attributeAndVaryingPrecisionES3 = attributeAndVaryingPrecisionES3Shader;
exports.layoutAttributeES3 = layoutAttributeES3Shader;
exports.outToGlFragColorES3 = outToGlFragColorES3Shader;
exports.smoothVaryingES3 = smoothVaryingES3Shader;
exports.outQualifierFragmentES3 = outQualifierFragmentES3Shader;
exports.ifdefFragment = ifdefFragmentShader;
exports.ifdef2Fragment = ifdef2FragmentShader;
