import Shaderity from './main/Shaderity';
import {
  AttributeSemantics,
  ReflectionAttribute,
  ReflectionUniform,
  ReflectionVarying,
  ShaderityObject,
  ShaderExtensionBehavior,
  ShaderConstantValueVarTypeES3,
  ShaderPrecisionObject,
  ShaderStageStr,
  ShaderPrecisionType,
  ShaderAttributeVarType,
  ShaderVaryingInterpolationType,
  ShaderVaryingVarType,
  ShaderUniformVarTypeES3,
  ShaderStructMemberObject,
  ShaderUBOVariableObject,
  ShaderVersion,
  TemplateObject,
  UniformSemantics,
  VarType,
} from './types/type';

export type {
  AttributeSemantics,
  ReflectionAttribute,
  ReflectionUniform,
  ReflectionVarying,
  ShaderityObject,
  ShaderExtensionBehavior,
  ShaderConstantValueVarTypeES3,
  ShaderPrecisionObject,
  ShaderStageStr,
  ShaderPrecisionType,
  ShaderAttributeVarType,
  ShaderVaryingInterpolationType,
  ShaderVaryingVarType,
  ShaderUniformVarTypeES3,
  ShaderStructMemberObject,
  ShaderUBOVariableObject,
  ShaderVersion,
  TemplateObject,
  UniformSemantics,
  VarType,
}

export default Shaderity
